---
title: "Research log remove spike"
author: "jliucx"
date: "2024-12-5"
output: 
  workflowr::wflow_html:
    number_sections: true
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72

---


```{r,include=F}

setwd("/project/xuanyao/jiaming/Getting_started")

library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(presto)
library(sceptre)
library(sceptredata)
library(readr)
library(dplyr)
library(Matrix)
library(parallel)
library(BH)
library(Rcpp)
library(peakRAM)
library(sgt)
library(heavytailcombtest)
library(gridExtra)
library(eulerr)
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(ACAT)
library(MASS)
source("code/functions_optimized.R")


gg_qqplot <- function(ps, ci = 0.95, title = "QQ Plot") {
  n <- length(ps)
  df <- data.frame(
    observed = pmin(-log10(sort(ps)), 4), # Cap observed values at 4
    expected = -log10(ppoints(n)),
    clower = pmin(-log10(qbeta(p = (1 - ci) / 2, shape1 = 1:n, shape2 = n:1)), 4), # Cap clower values at 4
    cupper = pmin(-log10(qbeta(p = (1 + ci) / 2, shape1 = 1:n, shape2 = n:1)), 4)  # Cap cupper values at 4
  )

  log10Pe <- expression(paste("Expected -log"[10], plain(P)))
  log10Po <- expression(paste("Observed -log"[10], plain(P)))

  ggplot(df) +
    geom_ribbon(mapping = aes(x = expected, ymin = clower, ymax = cupper), alpha = 0.1) +
    geom_point(aes(expected, observed), size = 1.5, color = "red") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.5) +
    xlab(log10Pe) + 
    ylab(log10Po) +
    ylim(0, 4) + # Limit y-axis to 0-5
    ggtitle(title) # Add title
}
```

# Morris our NMF

```{r,include=F}
gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris/program_data_NMF_set_300_50/gene_module_index_matrix.rds")

grna_target_data_frame_omit <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_discovery_analysis.rds")[,c(1,2,7)]
                 )
 perturbation_gene_strong_qc <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data_nature_cNMF/perturbation_gene_strong_qc_complete_gene.rds")

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]


library(eulerr)
```


```{r,include=F}
module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}

  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      
        module_genes <- setdiff(module_genes, remove_genes)

    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        # acat_pval <- ACAT(module_p_values)
        
     acat_pval <- combination.test(
  module_p_values[!is.na(module_p_values)],
  weights = NA,
  method = "Cauchy",
  tail.idx = 1
)


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]



library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))


max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")
```




```{r,include=F}
sceptre <- readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_calibration_check.rds")[,c(1,2,7)]

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide_2 <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide_2) <- sceptre_wide_2$grna_id
sceptre_wide_2 <- sceptre_wide_2[, -1]

sceptre_wide_2 <- sceptre_wide_2[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide_2)], ]

sceptre_wide_2 <- sceptre_wide_2[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide_2))) {
  grna_id <- rownames(sceptre_wide_2)[i]
  p_values_row <- sceptre_wide_2[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        # acat_pval <- ACAT(module_p_values)
        
     acat_pval <- combination.test(
  module_p_values[!is.na(module_p_values)],
  weights = NA,
  method = "Cauchy",
  tail.idx = 1
)


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre_NTC <- do.call(rbind, module_results)
module_results_sceptre_NTC <- module_results_sceptre_NTC[!is.na(module_results_sceptre_NTC$acat_pval), ]
```

```{r,echo=F}

max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_3000_wilcox_normal_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-4
max_stat_long_2 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_2 <- max_stat_long_2 %>% filter(!is.na(p_value))


max_stat_long_2 <- max_stat_long_2 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_2$bh_pval <-  p.adjust(max_stat_long_2$p_value, method = "BH")
max_stat_long_2$identifier <- paste(max_stat_long_2$grna_id, max_stat_long_2$module, sep = "_")

```


```{r,cache=F,fig.width=10,fig.height=10,echo=F}
library(eulerr)

significant_levels <- c(0.05)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

significant_ids_max_stat_2 <- na.omit(
  max_stat_long_2$identifier[max_stat_long_2$bh_pval < significant_level]
)



  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+ACAT` = significant_ids_gene_wise_p,
 
        `3000 current filter normal` = significant_ids_max_stat_2,
    `10000 current filter`=significant_ids_max_stat
 
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "blue", "yellow","green"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 1)

par(mfrow = c(1, 1))
```

```{r}
weak_rows <- which(max_stat_long$p_value > 0.6 & module_results_sceptre$acat_pval < 0.05)

strong_rows <- which(max_stat_long$p_value < module_results_sceptre$acat_pval & max_stat_long$p_value<0.1)

```



## Gene set distribution

```{r}
result_to_compare<-max_stat_long[weak_rows,]
result_to_analyze<-module_results_sceptre[weak_rows,]


result_to_compare_strong<-max_stat_long[strong_rows,]
result_to_analyze_strong<-module_results_sceptre[strong_rows,]
```
```{r,include=F}

plot_list <- list()

setwd("/project/xuanyao/jiaming/Getting_started/output/Morris/debug/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc")
for (i in 1:nrow(result_to_analyze)) {
  grna_id <- result_to_analyze$grna_id[i]
  gene_module <- result_to_analyze$module[i]
  
  acat_p <- result_to_analyze$acat_pval[i]
  our_p <- result_to_compare$p_value[i]
  
  row_idx <- which(rownames(max_stat) == grna_id)

  group_start <- floor((row_idx - 1) / 8) * 8 + 1
  group_end <- group_start + 7
  folder_name <- paste0(group_start, "_", group_end)


  chunk_idx <- row_idx - group_start + 1


  file_path <- file.path(folder_name, "max_statistics", paste0("max_statistics_chunk_", chunk_idx, ".rds"))


  ms <- readRDS(file_path)

    values <- ms[, gene_module, 1]
    highlight_value <- ms[1, gene_module, 1]
    
    df <- data.frame(values = values)
    
p <- ggplot(df, aes(x = values)) +
  geom_histogram(bins = 1000, fill = "lightgray", color = "black") +
  geom_vline(xintercept = highlight_value, color = "red", linewidth = 1) +
  ggtitle(paste0("Perturbation-geneset MaxStat test: ", grna_id, " - ", gene_module)) +
  xlab("Values") + ylab("Count") +
  annotate("text", x = Inf, y = Inf,
           hjust = 1.1, vjust = 1.5, size = 4, color = "blue",
           label = paste0("ACAT p = ", signif(acat_p, 3), 
                          "\nOur p = ", signif(our_p, 3))) +
  theme_minimal()

    
    plot_list[[i]] <- p

}

```





```{r,cache=F,fig.width=25, fig.height=100}
gridExtra::grid.arrange(grobs = plot_list, ncol = 3)
```


```{r}
genewise_p_combined_all <- readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/debug/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc/genewise_p_combined_all.rds")


 perturbation_gene_strong_qc_complete_gene <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data_nature_cNMF/perturbation_gene_strong_qc_complete_gene.rds")
```

## Genewise p value

### Where we are weak


```{r,include=F}
plot_list <- list()
hit_list <- list()  # 存储符合条件的 gene + metadata

for (i in 1:nrow(result_to_analyze)) {
  grna_id <- result_to_analyze$grna_id[i]
  gene_module <- result_to_analyze$module[i]
  gene_to_analyze <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, gene_module] == 1]
  
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
  
  gene_to_remove <- perturbation_gene_strong_qc_complete_gene[grna_id,2][[1]]
  gene_to_analyze <- setdiff(gene_to_analyze,gene_to_remove)
    gene_to_analyze <- setdiff(gene_to_analyze,cis_genes)

  
  y <- as.numeric(sceptre_wide[grna_id, gene_to_analyze])

  x <- as.numeric(genewise_p_combined_all[grna_id, gene_to_analyze])


  valid_idx <- which(!is.na(x) & !is.na(y))
  x <- x[valid_idx]
  y <- y[valid_idx]
  genes <- gene_to_analyze[valid_idx]

  df <- data.frame(our_method = x, sceptre = y, gene = genes)
  cor_val <- cor(x, y)
  proportion_significant_gene<- sum(x<0.05)/length(x)

  # hit_genes <- df$gene[df$our_method > 0.3 & df$sceptre < 0.05]
  hit_genes <- df$gene
  
  if (length(hit_genes) > 0) {
hit_list[[i]] <- data.frame(
  grna_id = grna_id,
  gene_module = gene_module,
  gene = I(list(hit_genes))
)
  }

  # 画图 + 添加相关系数
  p <- ggplot(df, aes(x = our_method, y = sceptre)) +
    geom_point(size = 2, alpha = 0.6) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
    annotate("text", x = 0.05, y = 0.95, label = paste0("cor = ", round(cor_val, 3)),
             hjust = 0, size = 5, color = "blue") +
      annotate("text", x = 0.05, y = 0.88, label = paste0("prop_sig = ", round(proportion_significant_gene, 3)),
           hjust = 0, size = 5, color = "blue")+
    labs(x = "Our method", y = "Sceptre",
         title = paste0("Perturbation-gene p values: ", grna_id, " - genes in ", gene_module)) +
    theme_bw()

  plot_list[[i]] <- p
}

```

```{r,cache=F,fig.width=25, fig.height=150}
gridExtra::grid.arrange(grobs = plot_list, ncol = 3)
```

### Where we are strong

```{r,include=F}
plot_list <- list()
hit_list <- list()  # 存储符合条件的 gene + metadata

for (i in 1:nrow(result_to_analyze_strong)) {
  grna_id <- result_to_analyze_strong$grna_id[i]
  gene_module <- result_to_analyze_strong$module[i]
  gene_to_analyze <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, gene_module] == 1]
  
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
  
  gene_to_remove <- perturbation_gene_strong_qc_complete_gene[grna_id,2][[1]]
  gene_to_analyze <- setdiff(gene_to_analyze,gene_to_remove)
    gene_to_analyze <- setdiff(gene_to_analyze,cis_genes)

  
  y <- as.numeric(sceptre_wide[grna_id, gene_to_analyze])

  x <- as.numeric(genewise_p_combined_all[grna_id, gene_to_analyze])


  valid_idx <- which(!is.na(x) & !is.na(y))
  x <- x[valid_idx]
  y <- y[valid_idx]
  genes <- gene_to_analyze[valid_idx]

  df <- data.frame(our_method = x, sceptre = y, gene = genes)
  cor_val <- cor(x, y)
  proportion_significant_gene<- sum(x<0.05)/length(x)

  # hit_genes <- df$gene[df$our_method > 0.3 & df$sceptre < 0.05]
  hit_genes <- df$gene
  
  if (length(hit_genes) > 0) {
hit_list[[i]] <- data.frame(
  grna_id = grna_id,
  gene_module = gene_module,
  gene = I(list(hit_genes))
)
  }

  # 画图 + 添加相关系数
  p <- ggplot(df, aes(x = our_method, y = sceptre)) +
    geom_point(size = 2, alpha = 0.6) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
    annotate("text", x = 0.05, y = 0.95, label = paste0("cor = ", round(cor_val, 3)),
             hjust = 0, size = 5, color = "blue") +
      annotate("text", x = 0.05, y = 0.88, label = paste0("prop_sig = ", round(proportion_significant_gene, 3)),
           hjust = 0, size = 5, color = "blue")+
    labs(x = "Our method", y = "Sceptre",
         title = paste0("Perturbation-gene p values: ", grna_id, " - genes in ", gene_module)) +
    theme_bw()

  plot_list[[i]] <- p
}

```

```{r,cache=F,fig.width=25, fig.height=120}
gridExtra::grid.arrange(grobs = plot_list, ncol = 3)
```

## Genewise distribution

```{r,warning=F,include=F}
plot_list <- list()


setwd("/project/xuanyao/jiaming/Getting_started/output/Morris/debug/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc")
for (i in 1:1) {
  grna_id <- result_to_analyze$grna_id[i]
  gene_list <- ((hit_list[[i]])[1,3])[[1]]
  
  
   if (length(gene_list)>0){
     
  row_idx <- which(rownames(max_stat) == grna_id)

  group_start <- floor((row_idx - 1) / 8) * 8 + 1
  group_end <- group_start + 7
  folder_name <- paste0(group_start, "_", group_end)


  chunk_idx <- row_idx - group_start + 1


  file_path <- file.path(folder_name, "normalized_test_tensor", paste0("normalized_test_tensor_chunk_", chunk_idx, ".rds"))


  ms <- readRDS(file_path)
  
 
  
  for (gene in gene_list){
    
    our_p <- genewise_p_combined_all[grna_id,gene]
    sceptre_p <- sceptre_wide[grna_id, gene]

    values <- ms[, which(rownames(gene_module_index_matrix)==gene), 1]
    values <- values[is.finite(values)]  

    highlight_value <- ms[1, which(rownames(gene_module_index_matrix)==gene), 1]
    
    df <- data.frame(values = values)
    
p <- ggplot(df, aes(x = values)) +
  geom_histogram(bins = 1000, fill = "lightgray", color = "black") +
  geom_vline(xintercept = highlight_value, color = "red", linewidth = 1) +
  ggtitle(paste0("Perturbation-gene Wilcoxon test: ", grna_id, " - ", gene)) +
  xlab("Values") + ylab("Count") +
  annotate("text", x = Inf, y = Inf,
           hjust = 1.1, vjust = 1.5, size = 4, color = "blue",
           label = paste0("Sceptre p = ", signif(sceptre_p, 3), 
                          "\nOur wilcoxon p = ", signif(our_p, 3))) +
  theme_minimal()

    
    plot_list[[(length(plot_list)+1)]] <- p
  }
  }

}

```


```{r,cache=F,fig.width=25, fig.height=150}
gridExtra::grid.arrange(grobs = plot_list, ncol = 3)
```
