---
title: "Research log June"
author: "jliucx"
date: "2025-6-1"
output: 
  workflowr::wflow_html:
    number_sections: true
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72

---
```{r,include=F}

setwd("/project/xuanyao/jiaming/Getting_started")

library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(presto)
library(sceptre)
library(sceptredata)
library(readr)
library(dplyr)
library(Matrix)
library(parallel)
library(BH)
library(Rcpp)
library(peakRAM)
library(sgt)
library(heavytailcombtest)
library(gridExtra)
library(eulerr)
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(ACAT)
library(MASS)
source("code/functions_optimized.R")


gg_qqplot <- function(ps, ci = 0.95, title = "QQ Plot") {
  n <- length(ps)
  df <- data.frame(
    observed = pmin(-log10(sort(ps)), 4), # Cap observed values at 4
    expected = -log10(ppoints(n)),
    clower = pmin(-log10(qbeta(p = (1 - ci) / 2, shape1 = 1:n, shape2 = n:1)), 4), # Cap clower values at 4
    cupper = pmin(-log10(qbeta(p = (1 + ci) / 2, shape1 = 1:n, shape2 = n:1)), 4)  # Cap cupper values at 4
  )

  log10Pe <- expression(paste("Expected -log"[10], plain(P)))
  log10Po <- expression(paste("Observed -log"[10], plain(P)))

  ggplot(df) +
    geom_ribbon(mapping = aes(x = expected, ymin = clower, ymax = cupper), alpha = 0.1) +
    geom_point(aes(expected, observed), size = 1.5, color = "red") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.5) +
    xlab(log10Pe) + 
    ylab(log10Po) +
    ylim(0, 4) + # Limit y-axis to 0-5
    ggtitle(title) # Add title
}
```



# Morris cNMF




## Strong perturbation-gene qc

```{r,include=F}
gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris/program_data_nature_cNMF/gene_module_index_matrix.rds")
grna_target_data_frame_omit <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_official_应该没啥问题了/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_discovery_analysis.rds")[,c(1,2,7)]
                 )
 perturbation_gene_strong_qc <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data_nature_cNMF/perturbation_gene_strong_qc.rds")

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]

library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))






max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")

sceptre <- readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_calibration_check.rds")[,c(1,2,7)]

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre_NTC <- do.call(rbind, module_results)
module_results_sceptre_NTC <- module_results_sceptre_NTC[!is.na(module_results_sceptre_NTC$acat_pval), ]
```




```{r,echo=F}

max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_with_bug/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-4
max_stat_long_2 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_2 <- max_stat_long_2 %>% filter(!is.na(p_value))


max_stat_long_2 <- max_stat_long_2 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_2$bh_pval <-  p.adjust(max_stat_long_2$p_value, method = "BH")
max_stat_long_2$identifier <- paste(max_stat_long_2$grna_id, max_stat_long_2$module, sep = "_")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov/cNMF_3000_skew_t_approximation/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-5
max_stat_long_3 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_3 <- max_stat_long_3 %>% filter(!is.na(p_value))


max_stat_long_3 <- max_stat_long_3 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_3$bh_pval <-  p.adjust(max_stat_long_3$p_value, method = "BH")
max_stat_long_3$identifier <- paste(max_stat_long_3$grna_id, max_stat_long_3$module, sep = "_")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_3000_wilcox_normal_approx_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-5
max_stat_long_4 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_4 <- max_stat_long_4 %>% filter(!is.na(p_value))


max_stat_long_4 <- max_stat_long_4 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_4$bh_pval <-  p.adjust(max_stat_long_4$p_value, method = "BH")
max_stat_long_4$identifier <- paste(max_stat_long_4$grna_id, max_stat_long_4$module, sep = "_")
max_stat_long_4 <- max_stat_long_4[match(max_stat_long_2$identifier, max_stat_long_4$identifier), ]


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-5
max_stat_long_5 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_5 <- max_stat_long_5 %>% filter(!is.na(p_value))


max_stat_long_5 <- max_stat_long_5 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_5$bh_pval <-  p.adjust(max_stat_long_5$p_value, method = "BH")
max_stat_long_5$identifier <- paste(max_stat_long_5$grna_id, max_stat_long_5$module, sep = "_")
```


```{r,cache=F,fig.width=16,fig.height=16,echo=F}
library(eulerr)

significant_levels <- c(0.05)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

significant_ids_max_stat_2 <- na.omit(
  max_stat_long_2$identifier[max_stat_long_2$bh_pval < significant_level]
)

significant_ids_max_stat_3 <- na.omit(
  max_stat_long_3$identifier[max_stat_long_3$bh_pval < significant_level]
)

significant_ids_max_stat_4 <- na.omit(
  max_stat_long_4$identifier[max_stat_long_4$bh_pval < significant_level]
)
significant_ids_max_stat_5 <- na.omit(
  max_stat_long_5$identifier[max_stat_long_5$bh_pval < significant_level]
)

  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+ACAT(truncated)` = significant_ids_gene_wise_p,
 
        `10000 original` = significant_ids_max_stat_2,
    `10000 current filter`=significant_ids_max_stat,
        `3000 current filter normal`=significant_ids_max_stat_4
 
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "blue", "yellow","green"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 1)

par(mfrow = c(1, 1))
```


## NTC

```{r,fig.width=18,fig.height=10,cache=F}
p1<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_official_应该没啥问题了/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 10000 no approximation")

p2<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_3000_wilcox_normal_approx_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 3000 normal approximation")

p3<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_with_bug/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="No filter, 10000 no approximation")

ntc_pvals <- module_results_sceptre_NTC$acat_pval
p4<-gg_qqplot(ntc_pvals, title="NTC-ACAT")
grid.arrange(p3,p1,p2,p4,ncol=2)
```




# Morris - HALLMARK



## Strong perturbation - gene qc

```{r,echo=F,include=F}
gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/gene_module_index_matrix.rds")
grna_target_data_frame_omit <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/HALLMARK_10000_wilcox_no_approx_perturbation_gene_remove_strong_official/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_discovery_analysis.rds")[,c(1,2,7)]
                 )
 perturbation_gene_qc <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data_nature_cNMF/perturbation_gene_strong_qc_complete_gene.rds")
 
 genewise_p_combined_all <- as.data.frame(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/debug/HALLMARK_10000_wilcox_no_approx_perturbation_gene_remove_strong_official/genewise_p_combined_all.rds"))

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_qc)) {
  remove_genes <- perturbation_gene_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
            module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        # print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      # print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]

library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))






max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")

max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov/HALLMARK_10000_no_approximation/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-4
max_stat_long_2 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_2 <- max_stat_long_2 %>% filter(!is.na(p_value))


max_stat_long_2 <- max_stat_long_2 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_2$bh_pval <-  p.adjust(max_stat_long_2$p_value, method = "BH")
max_stat_long_2$identifier <- paste(max_stat_long_2$grna_id, max_stat_long_2$module, sep = "_")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/HALLMARK_3000_wilcox_normal_approx_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-4
max_stat_long_3 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_3 <- max_stat_long_3 %>% filter(!is.na(p_value))


max_stat_long_3 <- max_stat_long_3 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_3$bh_pval <-  p.adjust(max_stat_long_3$p_value, method = "BH")
max_stat_long_3$identifier <- paste(max_stat_long_3$grna_id, max_stat_long_3$module, sep = "_")

sceptre <- readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_calibration_check.rds")[,c(1,2,7)]

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre_NTC <- do.call(rbind, module_results)
module_results_sceptre_NTC <- module_results_sceptre_NTC[!is.na(module_results_sceptre_NTC$acat_pval), ]

module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(genewise_p_combined_all ))) {
  

  grna_id <- rownames(genewise_p_combined_all)[i]
  p_values_row <- genewise_p_combined_all[i,] 
  

  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_qc)) {
  remove_genes <- perturbation_gene_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  
  
  
  
  
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 

            module_genes <- setdiff(module_genes, remove_genes)


    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  
      
      
      if (length(module_p_values) > 0) {
        # acat_pval <- ACAT(module_p_values)

     acat_pval <- combination.test(
  module_p_values[!is.na(module_p_values)],
  weights = NA,
  method = "Cauchy",
  tail.idx = 1
)


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        # print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      # print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_t <- do.call(rbind, module_results)

module_results_t <- module_results_t[!is.na(module_results_t$acat_pval), ]

module_results_t$acat_pval[module_results_t$acat_pval<1e-4] <- 1e-4

module_results_t <- module_results_t %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

```



```{r,cache=F}

selected_rows <- which(max_stat_long$p_value > 0.2 & module_results_sceptre$acat_pval < 0.05)

plot(-log10(module_results_t[selected_rows,]$acat_pval),
-log10(max_stat_long[selected_rows,]$p_value),xlab="wilcoxon+ACAT",ylab="wilcoxon+ours",main="Wilcoxon_ACAT vs Wilcoxon_Our for the red region(-log transformed)")

plot(-log10(module_results_t$acat_pval),
-log10(max_stat_long$p_value),xlab="wilcoxon+ACAT",ylab="wilcoxon+ours",main="Wilcoxon_ACAT vs Wilcoxon_Our for the red region(-log transformed)")

```


```{r,cache=F,fig.width=8,fig.height=8,echo=F}
library(eulerr)

significant_levels <- c(0.05)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

significant_ids_max_stat_2 <- na.omit(
  max_stat_long_2$identifier[max_stat_long_2$bh_pval < significant_level]
)

significant_ids_max_stat_3 <- na.omit(
  max_stat_long_3$identifier[max_stat_long_3$bh_pval < significant_level]
)
  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+Cauchy` = significant_ids_gene_wise_p,
    `remove spike strong qc`=significant_ids_max_stat,
        `remove spike strong qc normal`=significant_ids_max_stat_3,
    `not remove`=significant_ids_max_stat_2
 
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "yellow", "orange","blue"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 1)

par(mfrow = c(1, 1))
```

## NTC

```{r,fig.width=15,fig.height=7,cache=F}


p1<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_official_应该没啥问题了/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 10000 no approximation")

p2<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_3000_wilcox_normal_approx_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 3000 normal approximation")

p3<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/cNMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_with_bug/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="No filter, 10000 no approximation")



ntc_pvals <- module_results_sceptre_NTC$acat_pval
p4<-gg_qqplot(ntc_pvals, title="NTC-ACAT")
grid.arrange(p3,p1,p2,p4,ncol=2)

```

# Morris our NMF

## Strong perturbation-gene qc

```{r,include=F}
gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris/program_data_NMF_set_300_50/gene_module_index_matrix.rds")
grna_target_data_frame_omit <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_discovery_analysis.rds")[,c(1,2,7)]
                 )
 perturbation_gene_strong_qc <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data_nature_cNMF/perturbation_gene_strong_qc.rds")

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]

library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))






max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")

sceptre <- readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/author_threshold_updated/results_run_calibration_check.rds")[,c(1,2,7)]

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]

# sceptre_wide <- sceptre_wide[rowSums(grna_assignment_matrix_author_threshold[rownames(sceptre_wide),])>100,]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id  
  
if (grna_id %in% rownames(perturbation_gene_strong_qc)) {
  remove_genes <- perturbation_gene_strong_qc[grna_id, 2][[1]]
} else {
  remove_genes <- character(0)  # 空字符向量，不会影响 setdiff
}
  
  
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
      haha<-length(module_genes)
        module_genes <- setdiff(module_genes, remove_genes)

      
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      if (length(module_p_values) > 0) {
        acat_pval <- ACAT(module_p_values)
        
#      acat_pval <- combination.test(
#   module_p_values[!is.na(module_p_values)],
#   weights = NA,
#   method = "Cauchy",
#   tail.idx = 1
# )


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        print("dont have valid p values for that module")
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      
      print("dont have valid gene in that module")
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre_NTC <- do.call(rbind, module_results)
module_results_sceptre_NTC <- module_results_sceptre_NTC[!is.na(module_results_sceptre_NTC$acat_pval), ]


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_3000_wilcox_normal_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)
max_stat[max_stat==0]<- 1e-4
max_stat_long_2 <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long_2 <- max_stat_long_2 %>% filter(!is.na(p_value))


max_stat_long_2 <- max_stat_long_2 %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

max_stat_long_2$bh_pval <-  p.adjust(max_stat_long_2$p_value, method = "BH")
max_stat_long_2$identifier <- paste(max_stat_long_2$grna_id, max_stat_long_2$module, sep = "_")

```


```{r,cache=F,fig.width=10,fig.height=10,echo=F}
library(eulerr)

significant_levels <- c(0.05)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

significant_ids_max_stat_2 <- na.omit(
  max_stat_long_2$identifier[max_stat_long_2$bh_pval < significant_level]
)



  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+ACAT` = significant_ids_gene_wise_p,
 
        `3000 current filter normal` = significant_ids_max_stat_2,
    `10000 current filter`=significant_ids_max_stat
 
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "blue", "yellow","green"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 1)

par(mfrow = c(1, 1))
```

## NTC

```{r,fig.width=21,fig.height=7}
p1<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_10000_wilcox_no_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 10000 no approximation")

p2<-gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/our_NMF_3000_wilcox_normal_approx_sceptre_perturbation_gene_remove_strong_qc/resample_normal_test_statistics.csv",row.names = 1)[189:198,])), title="current filter, 3000 normal approximation")




ntc_pvals <- module_results_sceptre_NTC$acat_pval
p4<-gg_qqplot(ntc_pvals, title="NTC-ACAT")
grid.arrange(p1,p2,p4,ncol=3)
```

# NTC - Random gene set

```{r,fig.width=15,fig.height=7}


p5 <- gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/NTC_complete_set/Strong_qc_FAKE_NON_OVERLAP_set_70genes_per_set_3000_normal_wilcox/resample_normal_test_statistics.csv",row.names = 1))), title="filter, normal apprximation, 100 Non-overlapping fake sets, 70 genes per set")

p6 <- gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/NTC_complete_set/Strong_qc_FAKE_NON_OVERLAP_set_70genes_per_set_10000_no_wilcox/resample_normal_test_statistics.csv",row.names = 1))), title="filter, no apprximation, 100 Non-overlapping fake sets, 70 genes per set")


p3<-  gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/NTC_complete_set/NONOVERLAP_FAKE_set_70genes_per_set_3000_normal_wilcox/resample_normal_test_statistics.csv",row.names = 1))), title="No filter, normal apprximation, 100 Non-overlapping fake sets, 70 genes per set")

p4<-  gg_qqplot(as.vector(as.matrix(read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/remove_cis_match_grna/4_cov_high_expressed_gene/NTC_complete_set/NONOVERLAP_FAKE_set_70genes_per_set_10000_wilcox/resample_normal_test_statistics.csv",row.names = 1))), title="No filter, noapprximation, 100 Non-overlapping fake sets, 70 genes per set")


grid.arrange(p5,p6,p3,p4,ncol=2)
```




