---
title: "Research log"
author: "jliucx"
date: "2024-12-5"
output: 
  workflowr::wflow_html:
    number_sections: true
editor_options:
  chunk_output_type: inline
  markdown: 
    wrap: 72
header-includes:
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Apr 2025 - Morris: Different grna assignment strategies affects the Morris results.

We compare 3 configurations: EM Algorithm; cutoff=4; author threshold.

## 50 Hallmark gene sets

### Author threshold
\textcolor{red}{这是红色文字}


### EM algorithm

```{r,echo=F}
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(presto)
library(sceptre)
library(sceptredata)
library(readr)
library(dplyr)
library(Matrix)
library(parallel)
library(BH)
library(Rcpp)
library(peakRAM)
library(sgt)
library(heavytailcombtest)
library(gridExtra)
library(eulerr)
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)
library(ACAT)
library(MASS)


gg_qqplot <- function(ps, ci = 0.95, title = "QQ Plot") {
  n <- length(ps)
  df <- data.frame(
    observed = pmin(-log10(sort(ps)), 4), # Cap observed values at 4
    expected = -log10(ppoints(n)),
    clower = pmin(-log10(qbeta(p = (1 - ci) / 2, shape1 = 1:n, shape2 = n:1)), 4), # Cap clower values at 4
    cupper = pmin(-log10(qbeta(p = (1 + ci) / 2, shape1 = 1:n, shape2 = n:1)), 4)  # Cap cupper values at 4
  )

  log10Pe <- expression(paste("Expected -log"[10], plain(P)))
  log10Po <- expression(paste("Observed -log"[10], plain(P)))

  ggplot(df) +
    geom_ribbon(mapping = aes(x = expected, ymin = clower, ymax = cupper), alpha = 0.1) +
    geom_point(aes(expected, observed), size = 1.5, color = "red") +
    geom_abline(intercept = 0, slope = 1, alpha = 0.5) +
    xlab(log10Pe) + 
    ylab(log10Po) +
    ylim(0, 4) + # Limit y-axis to 0-5
    ggtitle(title) # Add title
}
```


```{r,echo=F}
infect_cell_threshold <- 30

gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris/program_data_hallmark/gene_module_index_matrix.rds")
grna_target_data_frame_omit <- readRDS("data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/system_comparison/em/50HALLMARK/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/em_corrected_cov/results_run_discovery_analysis.rds")[,c(1,2,7)],
                 readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/em_corrected_cov/results_run_calibration_check.rds")[,c(1,2,7)])

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id      
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      # Check if module_p_values still has values after removing NAs
      if (length(module_p_values) > 0) {
        # acat_pval <- ACAT(module_p_values)
        
     acat_pval <- combination.test(
  module_p_values[!is.na(module_p_values)],
  weights = NA,
  method = "Cauchy",
  tail.idx = 1
)


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]

library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))






max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")
```





```{r,cache=F,fig.width=8.8,fig.height=6,echo=F}
library(eulerr)

significant_levels <- c(0.01, 0.05, 0.1, 0.25)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+Cauchy` = significant_ids_gene_wise_p,
    `wilcoxon` = significant_ids_max_stat
    # `Sceptre+Bonfer` = significant_ids_gene_wise_p_bonfer,
    # `t+Bonfer`=significant_ids_gene_wise_p_t_bonfer
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "green", "yellow", "orange"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 2)

par(mfrow = c(1, 1))
```



```{r,cache=F}
gg_qqplot(as.vector(as.matrix(max_stat[189:198,])), title="NTC-Wilcoxon (Morris data)")
ntc_pvals <- module_results_sceptre$acat_pval[grepl("^NTC", module_results_sceptre$grna_id)]
gg_qqplot(ntc_pvals, title="NTC-ACAT (Morris data)")
```

### Cutoff4

```{r,echo=F}
library(ggplot2)
library(dplyr)
library(readr)
library(tibble)
library(tidyr)

infect_cell_threshold <- 30

gene_module_index_matrix <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris/program_data_hallmark/gene_module_index_matrix.rds")
grna_target_data_frame_omit <- readRDS("data/Morris_adjusted/program_data/grna_target_data_frame_omit.rds")


discovery_pairs_cis <- readRDS("/project/xuanyao/jiaming/Getting_started/data/Morris_adjusted/program_data/discovery_pairs_cis.rds")


max_stat <- read.csv("/project/xuanyao/jiaming/Getting_started/output/Morris/system_comparison/cutoff4/50HALLMARK/resample_normal_test_statistics.csv",row.names = 1)


sceptre <- rbind(readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/cutoff4_corrected_cov/results_run_discovery_analysis.rds")[,c(1,2,7)],
                 readRDS("/project/xuanyao/jiaming/Getting_started/output/Morris/sceptre_all_pairs/cutoff4_corrected_cov/results_run_calibration_check.rds")[,c(1,2,7)])

sceptre <- sceptre[!is.na(sceptre$p_value), ]
sceptre$p_value[sceptre$p_value == 1] <- 1 - 1e-6

sceptre_wide <- sceptre %>%
  pivot_wider(names_from = response_id, values_from = p_value) %>%
  as.data.frame()

# Set the row names to be the grna_id and remove the grna_id column
rownames(sceptre_wide) <- sceptre_wide$grna_id
sceptre_wide <- sceptre_wide[, -1]

sceptre_wide <- sceptre_wide[rownames(max_stat)[rownames(max_stat) %in% rownames(sceptre_wide)], ]

sceptre_wide <- sceptre_wide[, rownames(gene_module_index_matrix), drop = FALSE]


library(eulerr)




module_results <- list()

# Iterate over each row of t_gene_p_no_approximation to compute ACAT p-values for each module
for (i in seq_len(nrow(sceptre_wide))) {
  grna_id <- rownames(sceptre_wide)[i]
  p_values_row <- sceptre_wide[i,] 
  
  # Initialize an empty list to store ACAT p-values and module names for each module
  module_acat_pvals <- c()
  module_names <- c()
  matched_targets <- grna_target_data_frame_omit[grna_target_data_frame_omit$grna_id %in% grna_id, ]$grna_target
  cis_genes <- discovery_pairs_cis[discovery_pairs_cis$grna_target == matched_targets, ]$response_id      
  # Iterate over each module in gene_modules to combine p-values using ACAT
  for (j in 1:ncol(gene_module_index_matrix)) {
    
    
    module_name <- colnames(gene_module_index_matrix)[j]  # Get the module name

    module_genes <- rownames(gene_module_index_matrix)[gene_module_index_matrix[, j] == 1]
module_genes <- intersect(module_genes, colnames(p_values_row))
    
      module_genes <- setdiff(module_genes, cis_genes) 
    
    # Only apply ACAT if there are genes to combine and they are not NA
    if (length(module_genes) > 0) {
      module_p_values <- as.numeric(p_values_row[module_genes])
      module_p_values <- module_p_values[!is.na(module_p_values)]  # Remove NAs
      
      # Check if module_p_values still has values after removing NAs
      if (length(module_p_values) > 0) {
        # acat_pval <- ACAT(module_p_values)
        
     acat_pval <- combination.test(
  module_p_values[!is.na(module_p_values)],
  weights = NA,
  method = "Cauchy",
  tail.idx = 1
)


        module_acat_pvals <- c(module_acat_pvals, acat_pval)
        module_names <- c(module_names, module_name)
      } else {
        module_acat_pvals <- c(module_acat_pvals, NA)
        module_names <- c(module_names, module_name)
      }
    } else {
      module_acat_pvals <- c(module_acat_pvals, NA)
      module_names <- c(module_names, module_name)
    }
  }
  
  # Store results as a data frame in the list
  module_results[[i]] <- data.frame(
    grna_id = grna_id,
    module = module_names,
    acat_pval = module_acat_pvals
  )
}


# Combine all results into a single data frame
module_results_sceptre <- do.call(rbind, module_results)
module_results_sceptre <- module_results_sceptre[!is.na(module_results_sceptre$acat_pval), ]

library(tibble)

max_stat_long <- max_stat%>%
  rownames_to_column(var = "grna_id") %>% # Add row names as a column
  pivot_longer(cols = -grna_id, names_to = "module", values_to = "p_value")

# Remove rows with NA p-values
max_stat_long <- max_stat_long %>% filter(!is.na(p_value))






max_stat_long <- max_stat_long %>%
  semi_join(module_results_sceptre, by = c("grna_id", "module"))

module_results_sceptre$bh_pval <- p.adjust(module_results_sceptre$acat_pval, method = "BH")
module_results_sceptre$identifier <- paste(module_results_sceptre$grna_id, module_results_sceptre$module, sep = "_")



max_stat_long$bh_pval <-  p.adjust(max_stat_long$p_value, method = "BH")
max_stat_long$identifier <- paste(max_stat_long$grna_id, max_stat_long$module, sep = "_")
```





```{r,cache=F,fig.width=8.8,fig.height=6,echo=F}
library(eulerr)

significant_levels <- c(0.01, 0.05, 0.1, 0.25)
# significant_levels <- 0.01
plot_list <- list()

# Loop through significant levels and display plots
for (significant_level in significant_levels) {
  # Filter significant IDs for each method
significant_ids_gene_wise_p <- na.omit(
  module_results_sceptre$identifier[module_results_sceptre$bh_pval < significant_level]
)

significant_ids_max_stat <- na.omit(
  max_stat_long$identifier[max_stat_long$bh_pval < significant_level]
)

  
  # Prepare the sets
  venn_data <- list(
    `Sceptre+Cauchy` = significant_ids_gene_wise_p,
    `wilcoxon` = significant_ids_max_stat
    # `Sceptre+Bonfer` = significant_ids_gene_wise_p_bonfer,
    # `t+Bonfer`=significant_ids_gene_wise_p_t_bonfer
  )
  
  # Generate the Euler diagram and display it
euler_plot <- plot(
  euler(venn_data),
  fills = list(fill = c("red", "green", "yellow", "orange"), alpha = 0.5),
  edges = TRUE,
  quantities = TRUE,
  labels = list(font = 2, cex = 1.2, pos = 3), # 调整字体和位置
  main = paste("Significant level", significant_level)
)
plot_list[[length(plot_list) + 1]] <- euler_plot
}
grid.arrange(grobs = plot_list, ncol = 2)

par(mfrow = c(1, 1))
```



```{r,cache=F}
gg_qqplot(as.vector(as.matrix(max_stat[189:198,])), title="NTC-Wilcoxon (Morris data)")
ntc_pvals <- module_results_sceptre$acat_pval[grepl("^NTC", module_results_sceptre$grna_id)]
gg_qqplot(ntc_pvals, title="NTC-ACAT (Morris data)")
```
