---
title: "sceptre_example"
author: "jliucx"
date: "2024-07-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r}
library(sceptre)
library(sceptredata)
library(readr)
```

```{r}
# load the data, creating a sceptre_object
directories <- "data/GDO_threshold"
grna_target_data_frame <- data.frame(read_csv(paste0(directories,"/grna_target_data_frame.csv")))
grna_target_data_frame[c(1:4,176:180,189:195),]
```

```{r}
sceptre_object <- import_data_from_cellranger(
  directories = directories,
  moi = "high",
  grna_target_data_frame = grna_target_data_frame
)
```

```{r}
sceptre_object
```

```{r}
# construct the grna-gene pairs to analyze
positive_control_pairs <- construct_positive_control_pairs(sceptre_object)
positive_control_pairs
```

```{r}
discovery_pairs <- construct_cis_pairs(
  sceptre_object = sceptre_object,
  positive_control_pairs = positive_control_pairs,
  response_position_data_frame=gene_position_data_frame_grch37,
  distance_threshold = 5e6
)
head(discovery_pairs)
```

```{r}
sceptre_object <- sceptre_object |>  # |> is R's base pipe, similar to %>%
  set_analysis_parameters(
    discovery_pairs = discovery_pairs,
    positive_control_pairs = positive_control_pairs,
    side = "left"
  ) |> 
  assign_grnas(
    method = "thresholding",
    threshold = 1
  ) |> 
  run_calibration_check(parallel = TRUE) |> 
  run_power_check(parallel = TRUE) |> 
  run_discovery_analysis(parallel = TRUE)

# Write the results to disk
write_outputs_to_directory(sceptre_object, "output/sceptre_outputs_cis_threshold")
```

```{r}
discovery_result <- get_result(
  sceptre_object = sceptre_object,
  analysis = "run_discovery_analysis"
)
discovery_result[1:20,]
```

```{r}
print(sceptre_object)
```
