---
title: "try"
output: html_document
---

```{r}
library(sceptre)
library(sceptredata)
directories <- "data/STINGseq-v1_GDO"
features_dir<-paste0(directories,"/GSM5225859_STINGseq-v1_GDO.umi_thresholds.csv.gz")
```

```{r}
features_data <- read_csv(features_dir)

# Print the first few rows of the data
features_data
```

```{r}
directories <- "data/STINGseq-v1_GDO"
features_dir<-paste0(directories,"/GSM5225859_STINGseq-v1_GDO.features.tsv.gz")
matrix_data <- read_tsv(features_dir)
matrix_data[36601:36810,]
grna=matrix_data[36601:36810,]

```

```{r}
matrix_data[36601:36810,]

```

```{r}


```

```{r}
dir="data/STINGseq-v1_HTO/GSM5225858_STINGseq-v1_HTO.barcodes.tsv.gz"
barcode <- read_tsv(dir, col_names = F)  
(GDO_barcode=barcode)
```

```{r}
dir="data/STINGseq-v1_cDNA/features.tsv.gz"
barcode_data <- read_tsv(dir, col_names = F)  # Assuming the file has a header
(cDNA_barcode=barcode_data)

```

```{r}
dir="data/STINGseq-v1_GDO/GSM5225859_STINGseq-v1_GDO.features.tsv.gz"
barcode_data <- read_tsv(dir, col_names = F)  # Assuming the file has a header
barcode_data[36601:36811,]

```

```{r}
dir="data/STINGseq-v1_HTO/GSM5225858_STINGseq-v1_HTO.barcodes.tsv.gz"
barcode_data <- read_tsv(dir, col_names = F)  # Assuming the file has a header
(HTO_barcode=barcode_data[,1])
```

```{r}
min_length <- min(length(x), length(y), length(z))
x <- x[1:min_length,1]
y <- y[1:min_length,1]
z <- z[1:min_length,1]
diff_xy <- sum(x != y)
diff_xz <- sum(x != z)
diff_yz <- sum(y != z)

cat("Number of different elements between GDO and cDNA:", diff_xy, "\n")
cat("Number of different elements between GDO and HTO:", diff_xz, "\n")
cat("Number of different elements between cDNA and HTO:", diff_yz, "\n")
diff_all <- sum(x != y | x != z | y != z)
cat("Number of different elements across GDO, cDNA, and HTO:", diff_all, "\n")


```

```{r}

```
